/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#include <RtORB/cdrStream.h>
#define CONST const
#define rtorb_echo_COMMON
#include "rtorb_echo.h"

/** Interface Module definitions in rtorb_echo */

#ifndef ORBIT_IDL_C_IMODULE_rtorb_echo
/* List (Skels) */
/* Interface declarations (Skels) */
/* List (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_Echo_echoString(CORBA_Echo obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CORBA_string (*_impl_echoString)(PortableServer_Servant _servant, const CORBA_char * mesg, CORBA_Environment *ev))
{
  *(CORBA_string *)result = _impl_echoString (obj, *(const CORBA_char * *)argv[0], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_Echo_echoString2(CORBA_Echo obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CORBA_string (*_impl_echoString2)(PortableServer_Servant _servant, const CORBA_char * mesg, CORBA_string* res, CORBA_Environment *ev))
{
  *(CORBA_string *)result = _impl_echoString2 (obj, *(const CORBA_char * *)argv[0], *(CORBA_string* *)argv[1], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_Echo_echoString3(CORBA_Echo obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CORBA_string (*_impl_echoString3)(PortableServer_Servant _servant, CORBA_string* mesg, CORBA_Environment *ev))
{
  *(CORBA_string *)result = _impl_echoString3 (obj, (CORBA_string*)argv[0], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_Echo_plus(CORBA_Echo obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CORBA_long (*_impl_plus)(PortableServer_Servant _servant, CORBA_long x, CORBA_long y, CORBA_Environment *ev))
{
  *(CORBA_long *)result = _impl_plus (obj, *(CORBA_long *)argv[0], *(CORBA_long *)argv[1], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_Echo_plus2(CORBA_Echo obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    void (*_impl_plus2)(PortableServer_Servant _servant, CORBA_long x, CORBA_long y, CORBA_long* ans, CORBA_Environment *ev))
{
  _impl_plus2 (obj, *(CORBA_long *)argv[0], *(CORBA_long *)argv[1], *(CORBA_long* *)argv[2], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_Echo_divide(CORBA_Echo obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    CORBA_float (*_impl_divide)(PortableServer_Servant _servant, CORBA_float x, CORBA_float y, CORBA_Environment *ev))
{
  *(CORBA_float *)result = _impl_divide (obj, *(CORBA_float *)argv[0], *(CORBA_float *)argv[1], env);
}
/* End of Option declarations (Skels) */
/* Option declarations (Skels) */
void _RtORB_impl_Echo_divide2(CORBA_Echo obj,
    void **result, CORBA_Class_Method *m, void **argv, CORBA_Environment  *env,
    void (*_impl_divide2)(PortableServer_Servant _servant, CORBA_float x, CORBA_float y, CORBA_float* ans, CORBA_Environment *ev))
{
  _impl_divide2 (obj, *(CORBA_float *)argv[0], *(CORBA_float *)argv[1], *(CORBA_float* *)argv[2], env);
}
/* End of Option declarations (Skels) */
/* End of List (Skels) */
/* End of Interface declarations (Skels) */
/* End of List (Skels) */

#endif

/** TypeCode definitions in rtorb_echo */
/*  TypeCode in C (TC_CORBA_sequence_CORBA_string) */
#if  (TC_IMPL_TC_CORBA_sequence_CORBA_string == 1)   && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array1[] = { (CORBA_TypeCode)&TC_CORBA_string_struct };
/***   TC_CORBA_sequence_CORBA_string  ***/

#ifdef ORBIT_IDL_C_IMODULE_rtorb_echo
static
#endif
struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
  NULL, /* parent */
  tk_sequence,  /* kind */
  (char *)NULL,  /* repository_id */
  (char *)NULL,  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array1,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (anonTC_3) */
/*  TypeCode in C (TC_CORBA_sequence_CORBA_string) */
#if  (TC_IMPL_TC_CORBA_sequence_CORBA_string == 1)   && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static const CORBA_TypeCode anon_subtypes_array8[] = { (CORBA_TypeCode)&TC_CORBA_string_struct };
/***   TC_CORBA_sequence_CORBA_string  ***/

#ifdef ORBIT_IDL_C_IMODULE_rtorb_echo
static
#endif
struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
  NULL, /* parent */
  tk_sequence,  /* kind */
  (char *)NULL,  /* repository_id */
  (char *)NULL,  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array8,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (TC_EchoList) */
#if  (TC_IMPL_TC_EchoList == 1)   && !defined(TC_DEF_TC_EchoList)
#define TC_DEF_TC_EchoList 1
static const CORBA_TypeCode anon_subtypes_array11[] = { (CORBA_TypeCode)&TC_CORBA_sequence_CORBA_string_struct };
/***   TC_EchoList  ***/

#ifdef ORBIT_IDL_C_IMODULE_rtorb_echo
static
#endif
struct CORBA_TypeCode_struct TC_EchoList_struct = {
  NULL, /* parent */
  tk_alias,  /* kind */
  (char *)"IDL:EchoList:1.0",  /* repository_id */
  (char *)"EchoList",  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array11,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (TC_CORBA_sequence_CORBA_float) */
#if  (TC_IMPL_TC_CORBA_sequence_CORBA_float == 1)   && !defined(TC_DEF_TC_CORBA_sequence_CORBA_float)
#define TC_DEF_TC_CORBA_sequence_CORBA_float 1
static const CORBA_TypeCode anon_subtypes_array14[] = { (CORBA_TypeCode)&TC_CORBA_float_struct };
/***   TC_CORBA_sequence_CORBA_float  ***/

#ifdef ORBIT_IDL_C_IMODULE_rtorb_echo
static
#endif
struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_float_struct = {
  NULL, /* parent */
  tk_sequence,  /* kind */
  (char *)NULL,  /* repository_id */
  (char *)NULL,  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array14,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (anonTC_16) */
/*  TypeCode in C (TC_CORBA_sequence_CORBA_float) */
#if  (TC_IMPL_TC_CORBA_sequence_CORBA_float == 1)   && !defined(TC_DEF_TC_CORBA_sequence_CORBA_float)
#define TC_DEF_TC_CORBA_sequence_CORBA_float 1
static const CORBA_TypeCode anon_subtypes_array21[] = { (CORBA_TypeCode)&TC_CORBA_float_struct };
/***   TC_CORBA_sequence_CORBA_float  ***/

#ifdef ORBIT_IDL_C_IMODULE_rtorb_echo
static
#endif
struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_float_struct = {
  NULL, /* parent */
  tk_sequence,  /* kind */
  (char *)NULL,  /* repository_id */
  (char *)NULL,  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array21,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (TC_ValueList) */
#if  (TC_IMPL_TC_ValueList == 1)   && !defined(TC_DEF_TC_ValueList)
#define TC_DEF_TC_ValueList 1
static const CORBA_TypeCode anon_subtypes_array24[] = { (CORBA_TypeCode)&TC_CORBA_sequence_CORBA_float_struct };
/***   TC_ValueList  ***/

#ifdef ORBIT_IDL_C_IMODULE_rtorb_echo
static
#endif
struct CORBA_TypeCode_struct TC_ValueList_struct = {
  NULL, /* parent */
  tk_alias,  /* kind */
  (char *)"IDL:ValueList:1.0",  /* repository_id */
  (char *)"ValueList",  /* identifier */
  1,    /* member_count  */
  NULL,    /* member_name */ 
  (CORBA_TypeCode *)anon_subtypes_array24,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  MAX (Align_pointer, MAX (Align_long, MAX (Align_sequence, 1)))    /* alignment */

};
#endif

/*  TypeCode in C (TC_Echo) */
#if  (TC_IMPL_TC_Echo == 1)   && !defined(TC_DEF_TC_Echo)
#define TC_DEF_TC_Echo 1
/***   TC_Echo  ***/

#ifdef ORBIT_IDL_C_IMODULE_rtorb_echo
static
#endif
struct CORBA_TypeCode_struct TC_Echo_struct = {
  NULL, /* parent */
  tk_objref,  /* kind */
  (char *)"IDL:Echo:1.0",  /* repository_id */
  (char *)"Echo",  /* identifier */
  0,    /* member_count  */
  NULL,    /* member_name */ 
  NULL,   /* member_type */
  NULL,   /* member_label */
  CORBA_OBJECT_NIL,   /* discriminator */ 
  -1, /* default_index */
  0,     /* length */
  NULL,   /* content_type */
  0, 0,   /* fixed_digits, fixed_scale */
  NULL,   /* *member_visibility */
  NULL,   /* type_modifier */
  NULL,   /* *concrete_base_type */
  0,   /* size */  
  Align_pointer    /* alignment */

};
#endif


/** Class ID definitions in rtorb_echo */

#ifndef ORBIT_IDL_C_IMODULE_rtorb_echo
CORBA_unsigned_long Echo__classid = 0;
#endif

/* Interface type data */

static CORBA_IArg Echo_echoString__arginfo [] = {
	{ TC_CORBA_string,  CORBA_I_ARG_IN , (char *)"mesg" }
};
static CORBA_IArg Echo_echoString2__arginfo [] = {
	{ TC_CORBA_string,  CORBA_I_ARG_IN , (char *)"mesg" },
	{ TC_CORBA_string,  CORBA_I_ARG_OUT , (char *)"res" }
};
static CORBA_IArg Echo_echoString3__arginfo [] = {
	{ TC_CORBA_string,  CORBA_I_ARG_INOUT , (char *)"mesg" }
};
static CORBA_IArg Echo_plus__arginfo [] = {
	{ TC_CORBA_long,  CORBA_I_ARG_IN , (char *)"x" },
	{ TC_CORBA_long,  CORBA_I_ARG_IN , (char *)"y" }
};
static CORBA_IArg Echo_plus2__arginfo [] = {
	{ TC_CORBA_long,  CORBA_I_ARG_IN , (char *)"x" },
	{ TC_CORBA_long,  CORBA_I_ARG_IN , (char *)"y" },
	{ TC_CORBA_long,  CORBA_I_ARG_OUT , (char *)"ans" }
};
static CORBA_IArg Echo_divide__arginfo [] = {
	{ TC_CORBA_float,  CORBA_I_ARG_IN , (char *)"x" },
	{ TC_CORBA_float,  CORBA_I_ARG_IN , (char *)"y" }
};
static CORBA_IArg Echo_divide2__arginfo [] = {
	{ TC_CORBA_float,  CORBA_I_ARG_IN , (char *)"x" },
	{ TC_CORBA_float,  CORBA_I_ARG_IN , (char *)"y" },
	{ TC_CORBA_float,  CORBA_I_ARG_OUT , (char *)"ans" }
};
CORBA_Class_Method Echo__methods [] = {
	{
		(char *)"echoString",
		TC_CORBA_string, 
		 1, Echo_echoString__arginfo,  
		 0, NULL

	},	{
		(char *)"echoString2",
		TC_CORBA_string, 
		 2, Echo_echoString2__arginfo,  
		 0, NULL

	},	{
		(char *)"echoString3",
		TC_CORBA_string, 
		 1, Echo_echoString3__arginfo,  
		 0, NULL

	},	{
		(char *)"plus",
		TC_CORBA_long, 
		 2, Echo_plus__arginfo,  
		 0, NULL

	},	{
		(char *)"plus2",
TC_void, 
		 3, Echo_plus2__arginfo,  
		 0, NULL

	},	{
		(char *)"divide",
		TC_CORBA_float, 
		 2, Echo_divide__arginfo,  
		 0, NULL

	},	{
		(char *)"divide2",
TC_void, 
		 3, Echo_divide2__arginfo,  
		 0, NULL

	}
};
static char * Echo__base_itypes[] = {
	(char *)"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef ORBIT_IDL_C_IMODULE_rtorb_echo
static
#endif
CORBA_Class_Impl Echo__imp = {
    TC_Echo,
    (char *)"Echo",
    7,
    Echo__methods,
    1, (char **) Echo__base_itypes
};

/* C++ Methods */
#ifdef __cplusplus /* cc_output_methods */
#ifndef Defined_CORBA_sequence_CORBA_string
#define Defined_CORBA_sequence_CORBA_string TRUE
 CORBA_sequence_CORBA_string::CppSeq::ElemRef 
CORBA_sequence_CORBA_string::operator[](CORBA::ULong n)
{
  return CORBA_sequence_CORBA_string::CppSeq::element(this, (int)n);
}

 CORBA_sequence_CORBA_string::CppSeq::ElemRef 
CORBA_sequence_CORBA_string::operator[](CORBA::ULong n) const
{
  return CORBA_sequence_CORBA_string::CppSeq::element(this, (int)n );
}

 CORBA::ULong 
CORBA_sequence_CORBA_string::length(CORBA::ULong n)
{
  return CORBA_sequence_CORBA_string::CppSeq::length(this, n);
}

 CORBA_sequence_CORBA_string_type & 
CORBA_sequence_CORBA_string::operator=(const CppSeq &o)
{
  o.copyTo(*this);
  return *this;
}

 CORBA_sequence_CORBA_string_type & 
CORBA_sequence_CORBA_string::operator=(const CORBA_sequence_CORBA_string_type &o)
{
  CppSeq::copy(o, *this);
  return *this;
}

#endif /* Defined_CORBA_sequence_CORBA_string */
#ifndef Defined_CORBA_sequence_CORBA_float
#define Defined_CORBA_sequence_CORBA_float TRUE
 CORBA_sequence_CORBA_float::CppSeq::ElemRef 
CORBA_sequence_CORBA_float::operator[](CORBA::ULong n)
{
  return CORBA_sequence_CORBA_float::CppSeq::element(this, (int)n);
}

 CORBA_sequence_CORBA_float::CppSeq::ElemRef 
CORBA_sequence_CORBA_float::operator[](CORBA::ULong n) const
{
  return CORBA_sequence_CORBA_float::CppSeq::element(this, (int)n );
}

 CORBA::ULong 
CORBA_sequence_CORBA_float::length(CORBA::ULong n)
{
  return CORBA_sequence_CORBA_float::CppSeq::length(this, n);
}

 CORBA_sequence_CORBA_float_type & 
CORBA_sequence_CORBA_float::operator=(const CppSeq &o)
{
  o.copyTo(*this);
  return *this;
}

 CORBA_sequence_CORBA_float_type & 
CORBA_sequence_CORBA_float::operator=(const CORBA_sequence_CORBA_float_type &o)
{
  CppSeq::copy(o, *this);
  return *this;
}

#endif /* Defined_CORBA_sequence_CORBA_float */
#endif /* __cplusplus */
