/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "rtorb_echo.h"

/*  Interface  */
CORBA_string Echo_echoString(CORBA_Echo _obj, const CORBA_char * mesg, CORBA_Environment *ev)
{
  CORBA_string _ORBIT_retval;
  void * _args[1];
  _args[0] = (void *)&mesg;
  invokeMethod (_obj, &Echo__imp.methods[0], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
CORBA_string Echo_echoString2(CORBA_Echo _obj, const CORBA_char * mesg, CORBA_string* res, CORBA_Environment *ev)
{
  CORBA_string _ORBIT_retval;
  void * _args[2];
  _args[0] = (void *)&mesg;
  _args[1] = &res;
  invokeMethod (_obj, &Echo__imp.methods[1], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
CORBA_string Echo_echoString3(CORBA_Echo _obj, CORBA_string* mesg, CORBA_Environment *ev)
{
  CORBA_string _ORBIT_retval;
  void * _args[1];
  _args[0] = mesg;
  invokeMethod (_obj, &Echo__imp.methods[2], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
CORBA_long Echo_plus(CORBA_Echo _obj, CORBA_long x, CORBA_long y, CORBA_Environment *ev)
{
  CORBA_long _ORBIT_retval;
  void * _args[2];
  _args[0] = (void *)&x;
  _args[1] = (void *)&y;
  invokeMethod (_obj, &Echo__imp.methods[3], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
void Echo_plus2(CORBA_Echo _obj, CORBA_long x, CORBA_long y, CORBA_long* ans, CORBA_Environment *ev)
{
  void * _args[3];
  _args[0] = (void *)&x;
  _args[1] = (void *)&y;
  _args[2] = &ans;
  invokeMethod (_obj, &Echo__imp.methods[4], NULL, _args, ev );
}
CORBA_float Echo_divide(CORBA_Echo _obj, CORBA_float x, CORBA_float y, CORBA_Environment *ev)
{
  CORBA_float _ORBIT_retval;
  void * _args[2];
  _args[0] = (void *)&x;
  _args[1] = (void *)&y;
  invokeMethod (_obj, &Echo__imp.methods[5], (void **)&_ORBIT_retval, _args, ev );
  return _ORBIT_retval;
}
void Echo_divide2(CORBA_Echo _obj, CORBA_float x, CORBA_float y, CORBA_float* ans, CORBA_Environment *ev)
{
  void * _args[3];
  _args[0] = (void *)&x;
  _args[1] = (void *)&y;
  _args[2] = &ans;
  invokeMethod (_obj, &Echo__imp.methods[6], NULL, _args, ev );
}
/*  End of Interface  */


#if __cplusplus
Echo_ptr
Echo::_narrow(CORBA::Object_ptr obj)
{
  return CORBA_Narrow<Echo>::narrow(obj);
}

CORBA_string
 Echo::echoString(const CORBA_char * mesg)
{
  CORBA_string tmp =  Echo_echoString(this->_impl,CORBA_string_CppInArg(mesg), &this->ev);
  return CORBA_string_helper::_retnew(tmp);
}

CORBA_string
 Echo::echoString2(const CORBA_char * mesg, CORBA_string_out res)
{
  CORBA_string tmp =  Echo_echoString2(this->_impl,CORBA_string_CppInArg(mesg), CORBA_string_CppOutArg(res), &this->ev);
  return CORBA_string_helper::_retnew(tmp);
}

CORBA_string
 Echo::echoString3(CORBA_string& mesg)
{
  CORBA_string tmp =  Echo_echoString3(this->_impl,CORBA_string_CppInOutArg(mesg), &this->ev);
  return CORBA_string_helper::_retnew(tmp);
}

CORBA::Long
 Echo::plus(CORBA::Long x, CORBA::Long y)
{
  CORBA_long tmp =  Echo_plus(this->_impl,CORBA::Long_CppInArg(x), CORBA::Long_CppInArg(y), &this->ev);
  return CORBA::Long_helper::_retnew(tmp);
}

void
 Echo::plus2(CORBA::Long x, CORBA::Long y, CORBA::Long_out ans)
{
 Echo_plus2(this->_impl,CORBA::Long_CppInArg(x), CORBA::Long_CppInArg(y), CORBA::Long_CppOutArg(ans), &this->ev);
  return;
 }

CORBA_float
 Echo::divide(CORBA_float x, CORBA_float y)
{
  CORBA_float tmp =  Echo_divide(this->_impl,CORBA_float_CppInArg(x), CORBA_float_CppInArg(y), &this->ev);
  return CORBA_float_helper::_retnew(tmp);
}

void
 Echo::divide2(CORBA_float x, CORBA_float y, CORBA_float_out ans)
{
 Echo_divide2(this->_impl,CORBA_float_CppInArg(x), CORBA_float_CppInArg(y), CORBA_float_CppOutArg(ans), &this->ev);
  return;
 }

#endif /* __cplusplus */
