/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#ifndef rtorb_echo_H
#define rtorb_echo_H 1

/** TypeCode definitions */
/***************************/
#ifndef  TC_DEF_TC_CORBA_sequence_CORBA_string
#  define  TC_DEF_TC_CORBA_sequence_CORBA_string	1
#  ifdef __cplusplus
#    define  Defined_CORBA_sequence_CORBA_string	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_CORBA_sequence_CORBA_float
#  define  TC_DEF_TC_CORBA_sequence_CORBA_float	1
#  ifdef __cplusplus
#    define  Defined_CORBA_sequence_CORBA_float	1
#  endif /* __cplusplus */
#endif
/***************************/
/***************************/
#ifndef  TC_DEF_TC_Echo
#  define  TC_DEF_TC_Echo	1
#  ifdef __cplusplus
#    define  Defined_Echo	1
#  endif /* __cplusplus */
#endif
/***************************/
#endif /*  rtorb_echo_H */
