/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#ifndef rtorb_echo_H
#define rtorb_echo_H 1
#include <RtORB/corba.h>

#ifdef __cplusplus
#include <RtORB/corba.hh>
extern "C" {
#endif /* __cplusplus */


/** typedefs **/

/* List (Recursive) */
/** Declare Type  */
#if !defined(ORBIT_DECL_CORBA_sequence_CORBA_string)
#define ORBIT_DECL_CORBA_sequence_CORBA_string 1
#if !defined(_CORBA_sequence_CORBA_string_defined)
#define _CORBA_sequence_CORBA_string_defined 1
/* Typecode and allocator (CORBA_sequence_CORBA_string)*/
#if !defined(TC_IMPL_TC_CORBA_sequence_CORBA_string)
#define  TC_IMPL_TC_CORBA_sequence_CORBA_string	1
  extern struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct;
#define TC_CORBA_sequence_CORBA_string ((CORBA_TypeCode)&TC_CORBA_sequence_CORBA_string_struct)
#endif
#define CORBA_sequence_CORBA_string__alloc() ((CORBA_sequence_CORBA_string *)RtORB_typecode_alloc (TC_CORBA_sequence_CORBA_string))
#define CORBA_sequence_CORBA_string_allocbuf(l) ((CORBA_string*)RtORB__allocbuf (TC_CORBA_sequence_CORBA_string, (l)))
typedef struct CORBA_sequence_CORBA_string_type {
  CORBA_unsigned_long _maximum;
  CORBA_unsigned_long _length;
  CORBA_string* _buffer;
  CORBA_unsigned_long _release;

#ifdef __cplusplus
  CORBA_sequence_CORBA_string_type () {
    _length = 0;
    _maximum = 0;
    _buffer = NULL;
    _release = 0;
  }
  CORBA_sequence_CORBA_string_type (const CORBA_sequence_CORBA_string_type &o) {
    _length = 0;
    _maximum = 0;
    _buffer = NULL;
    _release = 0;
    CppSeq::copy(o, *this); }
  ~CORBA_sequence_CORBA_string_type () {
    if (_buffer) { RtORB_free_by_typecode_cpp(_type_code(),this,0); }
  }
  typedef CORBA_string Elem;
  typedef Elem & ElemRef;
  typedef CORBA_sequence::T_ElemRefHelper<Elem> ElemHelper;
  typedef CORBA_sequence::T_RefSeq<CORBA_sequence_CORBA_string_type, Elem, ElemHelper> CppSeq;
  ElemRef operator[](CORBA::ULong n);
  CppSeq::ElemRef operator[](CORBA::ULong n) const;
  CORBA::ULong length() const { return _length; }
  CORBA::ULong length(CORBA::ULong n);
  CORBA_sequence_CORBA_string_type & operator=(const CppSeq &o);
  CORBA_sequence_CORBA_string_type & operator=(const CORBA_sequence_CORBA_string_type &o);
 static CORBA_TypeCode_struct * _type_code() { return const_cast<CORBA_TypeCode_struct*>(&TC_CORBA_sequence_CORBA_string_struct); };
  void operator>>=(cdrStream &s) const{
    s.marshal_sequence(_buffer, _length, _type_code());
  }
  void operator<<=(cdrStream &s){
    if(this->_length > 0){
      RtORB_free_by_typecode_cpp(_type_code(), this, 0);
    }
     if(this->_buffer){
      RtORB_free(this->_buffer, " CORBA_sequence: operator <<=");
    }
     _length <<= s;
    _buffer = (CORBA_string *)s.unmarshal_sequence(_length, _type_code());
    _maximum = _length;
    _release = 0;
  }
#endif /* __cplusplus */
}CORBA_sequence_CORBA_string;
#endif

#endif
#if !defined(_EchoList_defined)
#define _EchoList_defined 1
typedef CORBA_sequence_CORBA_string EchoList;

#ifdef __cplusplus
namespace EchoList {
  typedef EchoList::CppSeq EchoList;
  typedef CORBA_sequence::T_Helper<EchoList, EchoList> EchoList_helper;
  typedef CORBA_sequence::T_CInArg<EchoList, EchoList> EchoList_CInArg;
  typedef CORBA_sequence::T_COutArg<EchoList, EchoList> EchoList_COutArg;
  typedef CORBA_sequence::T_CInOutArg<EchoList, EchoList> EchoList_CInOutArg;
  typedef CORBA_sequence::T_CppInArg<EchoList, EchoList> EchoList_CppInArg;
  typedef CORBA_sequence::T_CppOutArg<EchoList, EchoList> EchoList_CppOutArg;
  typedef CORBA_sequence::T_CppInOutArg<EchoList, EchoList> EchoList_CppInOutArg;
  typedef CORBA_sequence::T_Ptr<EchoList> EchoList_ptr;
  typedef CORBA_sequence::T_Var<EchoList> EchoList_var;
  typedef CORBA_sequence::T_SeqOut<EchoList> EchoList_out;
}
#endif /* __cplusplus */
/** TypeCode and allocator */
#if !defined(TC_IMPL_TC_EchoList)
#define  TC_IMPL_TC_EchoList	1
  extern struct CORBA_TypeCode_struct TC_EchoList_struct;
#define TC_EchoList ((CORBA_TypeCode)&TC_EchoList_struct)
#endif
#define EchoList__alloc() ((EchoList *)RtORB_typecode_alloc (TC_CORBA_sequence_CORBA_string))
#define EchoList_allocbuf(l) ((CORBA_string*)RtORB__allocbuf (TC_CORBA_sequence_CORBA_string, (l)))
#endif
/** End of Declare Type  */

/** Declare Type  */
#if !defined(ORBIT_DECL_CORBA_sequence_CORBA_float)
#define ORBIT_DECL_CORBA_sequence_CORBA_float 1
#if !defined(_CORBA_sequence_CORBA_float_defined)
#define _CORBA_sequence_CORBA_float_defined 1
/* Typecode and allocator (CORBA_sequence_CORBA_float)*/
#if !defined(TC_IMPL_TC_CORBA_sequence_CORBA_float)
#define  TC_IMPL_TC_CORBA_sequence_CORBA_float	1
  extern struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_float_struct;
#define TC_CORBA_sequence_CORBA_float ((CORBA_TypeCode)&TC_CORBA_sequence_CORBA_float_struct)
#endif
#define CORBA_sequence_CORBA_float__alloc() ((CORBA_sequence_CORBA_float *)RtORB_typecode_alloc (TC_CORBA_sequence_CORBA_float))
#define CORBA_sequence_CORBA_float_allocbuf(l) ((CORBA_float*)RtORB__allocbuf (TC_CORBA_sequence_CORBA_float, (l)))
typedef struct CORBA_sequence_CORBA_float_type {
  CORBA_unsigned_long _maximum;
  CORBA_unsigned_long _length;
  CORBA_float* _buffer;
  CORBA_unsigned_long _release;

#ifdef __cplusplus
  CORBA_sequence_CORBA_float_type () {
    _length = 0;
    _maximum = 0;
    _buffer = NULL;
    _release = 0;
  }
  CORBA_sequence_CORBA_float_type (const CORBA_sequence_CORBA_float_type &o) {
    _length = 0;
    _maximum = 0;
    _buffer = NULL;
    _release = 0;
    CppSeq::copy(o, *this); }
  ~CORBA_sequence_CORBA_float_type () {
    if (_buffer) { RtORB_free_by_typecode_cpp(_type_code(),this,0); }
  }
  typedef CORBA_float Elem;
  typedef Elem & ElemRef;
  typedef CORBA_sequence::T_ElemRefHelper<Elem> ElemHelper;
  typedef CORBA_sequence::T_RefSeq<CORBA_sequence_CORBA_float_type, Elem, ElemHelper> CppSeq;
  ElemRef operator[](CORBA::ULong n);
  CppSeq::ElemRef operator[](CORBA::ULong n) const;
  CORBA::ULong length() const { return _length; }
  CORBA::ULong length(CORBA::ULong n);
  CORBA_sequence_CORBA_float_type & operator=(const CppSeq &o);
  CORBA_sequence_CORBA_float_type & operator=(const CORBA_sequence_CORBA_float_type &o);
 static CORBA_TypeCode_struct * _type_code() { return const_cast<CORBA_TypeCode_struct*>(&TC_CORBA_sequence_CORBA_float_struct); };
  void operator>>=(cdrStream &s) const{
    s.marshal_sequence(_buffer, _length, _type_code());
  }
  void operator<<=(cdrStream &s){
    if(this->_length > 0){
      RtORB_free_by_typecode_cpp(_type_code(), this, 0);
    }
     if(this->_buffer){
      RtORB_free(this->_buffer, " CORBA_sequence: operator <<=");
    }
     _length <<= s;
    _buffer = (CORBA_float *)s.unmarshal_sequence(_length, _type_code());
    _maximum = _length;
    _release = 0;
  }
#endif /* __cplusplus */
}CORBA_sequence_CORBA_float;
#endif

#endif
#if !defined(_ValueList_defined)
#define _ValueList_defined 1
typedef CORBA_sequence_CORBA_float ValueList;

#ifdef __cplusplus
namespace ValueList {
  typedef ValueList::CppSeq ValueList;
  typedef CORBA_sequence::T_Helper<ValueList, ValueList> ValueList_helper;
  typedef CORBA_sequence::T_CInArg<ValueList, ValueList> ValueList_CInArg;
  typedef CORBA_sequence::T_COutArg<ValueList, ValueList> ValueList_COutArg;
  typedef CORBA_sequence::T_CInOutArg<ValueList, ValueList> ValueList_CInOutArg;
  typedef CORBA_sequence::T_CppInArg<ValueList, ValueList> ValueList_CppInArg;
  typedef CORBA_sequence::T_CppOutArg<ValueList, ValueList> ValueList_CppOutArg;
  typedef CORBA_sequence::T_CppInOutArg<ValueList, ValueList> ValueList_CppInOutArg;
  typedef CORBA_sequence::T_Ptr<ValueList> ValueList_ptr;
  typedef CORBA_sequence::T_Var<ValueList> ValueList_var;
  typedef CORBA_sequence::T_SeqOut<ValueList> ValueList_out;
}
#endif /* __cplusplus */
/** TypeCode and allocator */
#if !defined(TC_IMPL_TC_ValueList)
#define  TC_IMPL_TC_ValueList	1
  extern struct CORBA_TypeCode_struct TC_ValueList_struct;
#define TC_ValueList ((CORBA_TypeCode)&TC_ValueList_struct)
#endif
#define ValueList__alloc() ((ValueList *)RtORB_typecode_alloc (TC_CORBA_sequence_CORBA_float))
#define ValueList_allocbuf(l) ((CORBA_float*)RtORB__allocbuf (TC_CORBA_sequence_CORBA_float, (l)))
#endif
/** End of Declare Type  */

/** Interface (Echo)   */
#if !defined(ORBIT_DECL_Echo) && !defined(_Echo_defined)
# define ORBIT_DECL_Echo 1
# define _Echo_defined 1
typedef CORBA_Object CORBA_Echo;
typedef CORBA_Object Echo;

#ifdef __cplusplus
namespace Echo {;
  class Echo;
  typedef CORBA_interface::T_Ptr<Echo> Echo_ptr;
  typedef CORBA_interface::T_Var<Echo> Echo_var;
  typedef CORBA_interface::T_Helper<Echo, Echo_ptr> Echo_helper;
  typedef CORBA_interface::CInArg<Echo> Echo_CInArg;
  typedef Echo_helper Echo_COutArg;
  typedef Echo_helper Echo_CInOutArg;
  typedef Echo_helper Echo_CppInArg;
  typedef Echo_helper Echo_CppOutArg;
  typedef Echo_helper Echo_CppInOutArg;
}
#endif  /* __cplusplus */
extern CORBA_unsigned_long Echo__classid;
/*  TypeCode and alloc for Echo  */
#if !defined(TC_IMPL_TC_Echo)
#define  TC_IMPL_TC_Echo	1
  extern struct CORBA_TypeCode_struct TC_Echo_struct;
#define TC_Echo ((CORBA_TypeCode)&TC_Echo_struct)
#endif
#endif  /** Interface (Echo)   */


/* Interface (Recursive) */

/* List (Recursive) */

/* End of List (Recursive) */

/* End of Interface (Recursive) */

/* End of List (Recursive) */

/** POA structures **/
#ifndef _defined_POA_Echo
#define _defined_POA_Echo 1
typedef struct {
  void *_private;
  CORBA_string (*echoString)(PortableServer_Servant _servant, const CORBA_char * mesg, CORBA_Environment *ev);
  CORBA_string (*echoString2)(PortableServer_Servant _servant, const CORBA_char * mesg, CORBA_string* res, CORBA_Environment *ev);
  CORBA_string (*echoString3)(PortableServer_Servant _servant, CORBA_string* mesg, CORBA_Environment *ev);
  CORBA_long (*plus)(PortableServer_Servant _servant, CORBA_long x, CORBA_long y, CORBA_Environment *ev);
  void (*plus2)(PortableServer_Servant _servant, CORBA_long x, CORBA_long y, CORBA_long* ans, CORBA_Environment *ev);
  CORBA_float (*divide)(PortableServer_Servant _servant, CORBA_float x, CORBA_float y, CORBA_Environment *ev);
  void (*divide2)(PortableServer_Servant _servant, CORBA_float x, CORBA_float y, CORBA_float* ans, CORBA_Environment *ev);
} POA_Echo__epv;

typedef struct {
  PortableServer_ServantBase__epv *_base_epv;
  POA_Echo__epv *Echo_epv;
} POA_Echo__vepv;

typedef struct {
  void *_private;
  POA_Echo__vepv *vepv;
} POA_Echo;

extern CORBA_Echo impl_Echo__create(PortableServer_POA servant, CORBA_Environment *ev);
extern impl_POA_ServantBase * impl_Echo__create_servant(PortableServer_POA servant, CORBA_Environment *ev);
extern void POA_Echo__init(PortableServer_Servant servant, CORBA_Environment *ev);
extern void POA_Echo__fini(PortableServer_Servant servant, CORBA_Environment *ev);
#endif /* _defined_POA_Echo */


/** skel prototypes **/
/*   List */
void _RtORB_impl_Echo_echoString(CORBA_Echo _obj, void * *result, CORBA_Class_Method *_m, void * *argv,CORBA_Environment *ev, CORBA_string (*_impl_echoString)(PortableServer_Servant _servant, const CORBA_char * mesg, CORBA_Environment *ev));
void _RtORB_impl_Echo_echoString2(CORBA_Echo _obj, void * *result, CORBA_Class_Method *_m, void * *argv,CORBA_Environment *ev, CORBA_string (*_impl_echoString2)(PortableServer_Servant _servant, const CORBA_char * mesg, CORBA_string* res, CORBA_Environment *ev));
void _RtORB_impl_Echo_echoString3(CORBA_Echo _obj, void * *result, CORBA_Class_Method *_m, void * *argv,CORBA_Environment *ev, CORBA_string (*_impl_echoString3)(PortableServer_Servant _servant, CORBA_string* mesg, CORBA_Environment *ev));
void _RtORB_impl_Echo_plus(CORBA_Echo _obj, void * *result, CORBA_Class_Method *_m, void * *argv,CORBA_Environment *ev, CORBA_long (*_impl_plus)(PortableServer_Servant _servant, CORBA_long x, CORBA_long y, CORBA_Environment *ev));
void _RtORB_impl_Echo_plus2(CORBA_Echo _obj, void * *result, CORBA_Class_Method *_m, void * *argv,CORBA_Environment *ev, void (*_impl_plus2)(PortableServer_Servant _servant, CORBA_long x, CORBA_long y, CORBA_long* ans, CORBA_Environment *ev));
void _RtORB_impl_Echo_divide(CORBA_Echo _obj, void * *result, CORBA_Class_Method *_m, void * *argv,CORBA_Environment *ev, CORBA_float (*_impl_divide)(PortableServer_Servant _servant, CORBA_float x, CORBA_float y, CORBA_Environment *ev));
void _RtORB_impl_Echo_divide2(CORBA_Echo _obj, void * *result, CORBA_Class_Method *_m, void * *argv,CORBA_Environment *ev, void (*_impl_divide2)(PortableServer_Servant _servant, CORBA_float x, CORBA_float y, CORBA_float* ans, CORBA_Environment *ev));
/*   End of List */

/** stub prototypes **/
/*   List  */
/*   Interface  */
CORBA_string Echo_echoString(CORBA_Echo _obj, const CORBA_char * mesg, CORBA_Environment *ev) ;
CORBA_string Echo_echoString2(CORBA_Echo _obj, const CORBA_char * mesg, CORBA_string* res, CORBA_Environment *ev) ;
CORBA_string Echo_echoString3(CORBA_Echo _obj, CORBA_string* mesg, CORBA_Environment *ev) ;
CORBA_long Echo_plus(CORBA_Echo _obj, CORBA_long x, CORBA_long y, CORBA_Environment *ev) ;
void Echo_plus2(CORBA_Echo _obj, CORBA_long x, CORBA_long y, CORBA_long* ans, CORBA_Environment *ev) ;
CORBA_float Echo_divide(CORBA_Echo _obj, CORBA_float x, CORBA_float y, CORBA_Environment *ev) ;
void Echo_divide2(CORBA_Echo _obj, CORBA_float x, CORBA_float y, CORBA_float* ans, CORBA_Environment *ev) ;
/*   End of List  */

extern CORBA_Class_Impl Echo__imp;
#define Echo_IMETHODS_LEN 7
extern CORBA_Class_Method Echo__methods[Echo_IMETHODS_LEN];

 /** for C++ **/
#ifdef __cplusplus
}

/** C++ class definition(skels)  **/
/* orbit-idl-cpp-headers.c(79) */
#ifndef Echo_impl_cpp_type_defined
#define Echo_impl_cpp_type_defined

class Echo;
class Echo__impl : 
  public virtual CORBA::Object
{
  public:
    Echo__impl() {}
    virtual CORBA_string echoString(const CORBA_char * mesg)=0;
    virtual CORBA_string echoString2(const CORBA_char * mesg, CORBA_string_out res)=0;
    virtual CORBA_string echoString3(CORBA_string& mesg)=0;
    virtual CORBA::Long plus(CORBA::Long x, CORBA::Long y)=0;
    virtual void plus2(CORBA::Long x, CORBA::Long y, CORBA::Long_out ans)=0;
    virtual CORBA_float divide(CORBA_float x, CORBA_float y)=0;
    virtual void divide2(CORBA_float x, CORBA_float y, CORBA_float_out ans)=0;
};

#endif /* Echo_impl_cpp_type_defined */


/** C++ class definition(stubs)  **/
/*  C++ stub List */
/*  C++ stub Interface */
#ifndef Echo_Echo_def
#define Echo_Echo_def

class Echo : 
  public virtual CORBA::Object
{
  public:
    typedef Echo _c_type;
    typedef Echo_ptr _ptr_type;
    typedef Echo_var _var_type;

    typedef Echo_helper _helper_type;

  public:
    typedef CORBA::Object _super_type;
  protected:
    Echo() : _super_type() {}

  public:
    Echo(CORBA_Object impl) : CORBA::Object(impl) {}

    Echo * operator->() { return this; };
    Echo & operator=(CORBA_Object);
    static Echo_ptr _narrow(CORBA::Object_ptr ptr);
    static Echo_ptr _duplicate(Echo_ptr ptr) {
      return CORBA_interface::Utils<Echo>::duplicate(ptr);
    }
    CORBA_string echoString(const CORBA_char * mesg) ;
    CORBA_string echoString2(const CORBA_char * mesg, CORBA_string_out res) ;
    CORBA_string echoString3(CORBA_string& mesg) ;
    CORBA::Long plus(CORBA::Long x, CORBA::Long y) ;
    void plus2(CORBA::Long x, CORBA::Long y, CORBA::Long_out ans) ;
    CORBA_float divide(CORBA_float x, CORBA_float y) ;
    void divide2(CORBA_float x, CORBA_float y, CORBA_float_out ans) ;
};


#ifndef Echo_operators_defined
#define Echo_operators_defined

inline void operator<<=(CORBA_any &any, Echo_ptr from_)
{
  CORBA_TypeCode tc = TC_CORBA_Object;
  CORBA_Object val = from_.impl();
  CORBA::AnyObjectStream::from(any, tc, val);
}

#endif /* Echo_operators_defined */ 


#endif /* Echo_Echo_def */


/** C++ class definition(POA)  **/

/** C++ class definition(global fumctions)  **/
#endif /* __cplusplus */

#endif
